{
 "title": "Error Messages & Api Key Quota",
 "tags": [
  "youtube",
  "error"
 ],
 "time": { "from": "now-14d/d", "to": "now/d" },
 "templating": {
  "list": [
   {
    "name": "process_group",
    "label": "Process Group",
    "query": "WITH cte_error_process_group AS (\nSELECT DISTINCT\n  error_process_group\nFROM\n  youtube_stats.error_messages\nORDER BY\n  error_process_group\n)\nSELECT\n  error_process_group\nFROM\n  cte_error_process_group\nUNION ALL\nSELECT\n 'no data' AS error_process_group\nFROM\n  (SELECT 1) a\nLEFT JOIN\n  cte_error_process_group b ON FALSE\nWHERE\n  NOT EXISTS (SELECT 1 FROM cte_error_process_group)"
   },
   {
    "name": "processor",
    "label": "Processor",
    "query": "WITH cte_error_processor AS (\nSELECT DISTINCT\n  error_processor\nFROM\n  youtube_stats.error_messages\nORDER BY\n  error_processor\n)\nSELECT\n  error_processor\nFROM\n  cte_error_processor\nUNION ALL\nSELECT\n 'no data' AS error_processor\nFROM\n  (SELECT 1) a\nLEFT JOIN\n  cte_error_processor b ON FALSE\nWHERE\n  NOT EXISTS (SELECT 1 FROM cte_error_processor)"
   },
   {
    "name": "api_keys",
    "query": "WITH cte_api_key_id AS (\nSELECT\n  api_key_id\nFROM\n  youtube_stats.api_key_quota\nORDER BY\n  api_key_id\n)\nSELECT\n  api_key_id\nFROM\n  cte_api_key_id\nUNION ALL\nSELECT\n 0 AS api_key_id\nFROM\n  (SELECT 1) a\nLEFT JOIN\n  cte_api_key_id b ON FALSE\nWHERE\n  NOT EXISTS (SELECT 1 FROM cte_api_key_id)"
   }
  ]
 },
 "panels": [
  { "title": "Error Messages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Error History",
   "type": "table",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  error_timestamp AS \"Timestamp\",\n  error_process_group AS \"Process Group\",\n  error_processor AS \"Processor\",\n  error_flowfile_content AS \"Flowfile Content\",\n  error_metadata AS \"Error Metadata\"\nFROM\n  youtube_stats.error_messages\nWHERE\n  $__timeFilter(error_timestamp) AND\n  error_process_group IN ($process_group) AND\n  error_processor IN ($processor)\nORDER BY\n  error_timestamp DESC"
    }
   ]
  },
  {
   "title": "Daily Errors by Process Group",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "WITH cte_raw_data AS (\nSELECT\n  error_process_group,\n  error_timestamp,\n  1 as intensity\nFROM\n  youtube_stats.error_messages\nWHERE\n  $__timeFilter(error_timestamp) AND\n  error_process_group IN ($process_group) AND\n  error_processor IN ($processor)\n), cte_data_with_default_values AS (\nSELECT\n  *\nFROM\n  cte_raw_data\nUNION ALL\nSELECT\n  d.error_process_group,\n  gs,\n  0 AS intensity -- For the data to be sorted we need all videos to have a value in all months (even if it is 0).\nFROM\n  (SELECT DISTINCT error_process_group FROM cte_raw_data) d,\n  generate_series(DATE($__timeFrom()::timestamp with time zone), DATE($__timeTo()::timestamp with time zone), INTERVAL '1 day') gs\n), cte_result AS (\nSELECT \n  TO_CHAR(error_timestamp, 'yyyy-mm-dd') AS day,\n  error_process_group,\n  SUM(intensity) AS daily_errors\nFROM\n  cte_data_with_default_values\nGROUP BY\n  day, error_process_group\nORDER BY\n  day ASC,\n  error_process_group ASC\n)\nSELECT\n  day,\n  error_process_group,\n  daily_errors\nFROM\n  cte_result\nUNION ALL\nSELECT\n '2000-01-01' AS day,\n 'no data' AS error_process_group,\n 0 AS daily_errors\nFROM\n  (SELECT 1) a\nLEFT JOIN\n  cte_result b ON FALSE\nWHERE\n  NOT EXISTS (SELECT 1 FROM cte_result)"
    }
   ]
  },
  {
   "title": "Daily Errors by Processor",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "rawSql": "WITH cte_raw_data AS (\nSELECT\n  error_processor,\n  error_timestamp,\n  1 as intensity\nFROM\n  youtube_stats.error_messages\nWHERE\n  $__timeFilter(error_timestamp) AND\n  error_process_group IN ($process_group) AND\n  error_processor IN ($processor)\n), cte_data_with_default_values AS (\nSELECT\n  *\nFROM\n  cte_raw_data\nUNION ALL\nSELECT\n  d.error_processor,\n  gs,\n  0 AS intensity -- For the data to be sorted we need all videos to have a value in all months (even if it is 0).\nFROM\n  (SELECT DISTINCT error_processor FROM cte_raw_data) d,\n  generate_series(DATE($__timeFrom()::timestamp with time zone), DATE($__timeTo()::timestamp with time zone), INTERVAL '1 day') gs\n), cte_result AS (\nSELECT \n  TO_CHAR(error_timestamp, 'yyyy-mm-dd') AS day,\n  error_processor,\n  SUM(intensity) AS daily_errors\nFROM\n  cte_data_with_default_values\nGROUP BY\n  day, error_processor\nORDER BY\n  day ASC,\n  error_processor ASC\n)\nSELECT\n  day,\n  error_processor,\n  daily_errors\nFROM\n  cte_result\nUNION ALL\nSELECT\n '2000-01-01' AS day,\n 'no data' AS error_processor,\n 0 AS daily_errors\nFROM\n  (SELECT 1) a\nLEFT JOIN\n  cte_result b ON FALSE\nWHERE\n  NOT EXISTS (SELECT 1 FROM cte_result)"
    }
   ]
  },
  { "title": "Api Keys", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 33 },
   "repeat": "api_keys",
   "targets": [
    {
     "rawSql": "SELECT\n  api_key AS \"Api Key\",\n  api_key_restart_date AS \"Latest Restart Date\"\nFROM\n  youtube_stats.api_key_quota\nWHERE\n  api_key_id = $api_keys"
    }
   ]
  },
  {
   "title": "Api Key Quota",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 36 },
   "repeat": "api_keys",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  api_key_quota\nFROM\n  youtube_stats.api_key_quota\nWHERE\n  api_key_id = $api_keys"
    }
   ]
  }
 ]
}