{
 "title": "Youtube Channel Analysis",
 "tags": [
  "youtube",
  "channel"
 ],
 "time": { "from": "now-14d/d", "to": "now/d" },
 "templating": {
  "list": [
   {
    "name": "channel_info__channel_name",
    "label": "Channel Name",
    "query": "WITH cte_channel_name AS (\nSELECT\n  channel_name\nFROM\n  youtube_stats.channel_info\nORDER BY\n  channel_name ASC\n)\nSELECT\n  channel_name\nFROM\n  cte_channel_name\nUNION ALL\nSELECT\n 'no data' AS channel_name\nFROM\n  (SELECT 1) a\nLEFT JOIN\n  cte_channel_name b ON FALSE\nWHERE\n  NOT EXISTS (SELECT 1 FROM cte_channel_name)"
   },
   { "name": "limit", "label": "Video Limit", "query": "5,10,15,20" }
  ]
 },
 "panels": [
  { "title": "${channel_info__channel_name}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "channel_info__channel_name" },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  vi.video_title,\n  vs.view_count\nFROM\n  youtube_stats.channel_info ci\nINNER JOIN\n  youtube_stats.video_info vi\nON\n  (vi.channel_id = ci.channel_id)\nINNER JOIN\n  youtube_stats.video_stats vs\nON\n  (vi.video_id = vs.video_id)\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  ci.channel_name IN ($channel_info__channel_name) AND\n  vs.\"timestamp\" = (SELECT MAX(\"timestamp\") FROM youtube_stats.video_stats WHERE video_id = vi.video_id)\nORDER BY\n  vs.view_count DESC\nLIMIT 10\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  vi.video_title,\n  vs.view_count\nFROM\n  youtube_stats.channel_info ci\nINNER JOIN\n  youtube_stats.video_info vi\nON\n  (vi.channel_id = ci.channel_id)\nINNER JOIN\n  youtube_stats.video_stats vs\nON\n  (vi.video_id = vs.video_id)\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  ci.channel_name IN ($channel_info__channel_name) AND\n  vs.\"timestamp\" = (SELECT MAX(\"timestamp\") FROM youtube_stats.video_stats WHERE video_id = vi.video_id)\nORDER BY\n  vs.view_count DESC\nLIMIT 10\nOFFSET 10\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  vi.video_title,\n  vs.view_count\nFROM\n  youtube_stats.channel_info ci\nINNER JOIN\n  youtube_stats.video_info vi\nON\n  (vi.channel_id = ci.channel_id)\nINNER JOIN\n  youtube_stats.video_stats vs\nON\n  (vi.video_id = vs.video_id)\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  ci.channel_name IN ($channel_info__channel_name) AND\n  vs.\"timestamp\" = (SELECT MAX(\"timestamp\") FROM youtube_stats.video_stats WHERE video_id = vi.video_id)\nORDER BY\n  vs.view_count DESC\nLIMIT 10\nOFFSET 20\n"
    }
   ]
  },
  {
   "title": "Top $limit Videos",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "WITH cte_video_list AS (\nSELECT DISTINCT\n  vi.video_id,\n  vi.video_title,\n  vi.video_creation_date,\n  MAX(vs.view_count)\nFROM\n  youtube_stats.channel_info ci\nINNER JOIN\n  youtube_stats.video_info vi\nUSING\n  (channel_id)\nINNER JOIN\n  youtube_stats.video_stats vs\nUSING\n  (video_id)\nWHERE\n  ci.channel_name IN ($channel_info__channel_name) AND\n  $__timeFilter(vs.\"timestamp\")\nGROUP BY\n  vi.video_id,\n  vi.video_title,\n  vi.video_creation_date\nORDER BY\n  MAX(vs.view_count) DESC\nLIMIT $limit\n), cte_tag AS (\nSELECT\n  vi.video_title,\n  MAX(vs.view_count) AS view_count,\n  tag\nFROM\n  cte_video_list vi\nINNER JOIN\n  youtube_stats.video_stats vs\nUSING\n  (video_id),\n  generate_series (\n    time_bucket(\n      '1 day', \n      (select timezone('Europe/Madrid', $__timeFrom()::timestamp with time zone))\n    ), time_bucket(\n      '1 day', \n      (select timezone('Europe/Madrid', $__timeTo()::timestamp with time zone))\n    ), '1 day'\n  ) tag\nWHERE\n  vs.timestamp >= tag AND\n  vs.timestamp <= tag + interval '1 day'\nGROUP BY\n  vi.video_title, tag\n)\nSELECT\n  video_title,\n  AVG(view_count) AS \"View Count\",\n  tag AS time\nFROM\n  cte_tag\nGROUP BY\n  video_title, tag\nORDER BY\n  time, MAX(view_count)"
    }
   ]
  },
  {
   "title": "Ranking by Creation Date",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "WITH cte_video_list AS (\nSELECT DISTINCT\n  vi.video_title,\n  vi.video_creation_date,\n  MAX(vs.view_count) AS view_count\nFROM\n  youtube_stats.channel_info ci\nINNER JOIN\n  youtube_stats.video_info vi\nUSING\n  (channel_id)\nINNER JOIN\n  youtube_stats.video_stats vs\nUSING\n  (video_id)\nWHERE\n  ci.channel_name IN ($channel_info__channel_name) AND\n  $__timeFilter(vs.\"timestamp\")\nGROUP BY\n  vi.video_id,\n  vi.video_title,\n  vi.video_creation_date\nORDER BY\n  MAX(vs.view_count) DESC\nLIMIT $limit\n), cte_rank AS (\nSELECT\n  video_title,\n  TO_CHAR(video_creation_date, 'YYYY-MM-DD') AS video_creation_date,\n  RANK() OVER (ORDER BY view_count DESC) AS rank_views,\n  RANK() OVER (ORDER BY video_creation_date ASC) AS rank_date\nFROM\n  cte_video_list\n)\nSELECT\n  video_title AS \"Video Title\",\n  video_creation_date AS \"Video Creation Date\",\n  rank_views AS \"Rank\",\n-- Ratio between video release date and position in the rankings\n  CASE\n    WHEN ((rank_date - rank_views)::DECIMAL)/$limit*100 >= 60 THEN '↑↑'\n    WHEN ((rank_date - rank_views)::DECIMAL)/$limit*100 >= 30 THEN '↑'\n    WHEN ((rank_date - rank_views)::DECIMAL)/$limit*100 >= 0 THEN '-'\n    WHEN ((rank_date - rank_views)::DECIMAL)/$limit*100 >= -30 THEN '-'\n    WHEN ((rank_date - rank_views)::DECIMAL)/$limit*100 >= -60 THEN '↓'\n    ELSE '↓↓'\n  END AS \"Recent Changes in Top\"\nFROM\n  cte_rank\nORDER BY\n  rank_views"
    }
   ]
  },
  {
   "title": "Top $limit Daily Views Videos",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "WITH cte_video_list AS (\nSELECT DISTINCT\n  vi.video_id,\n  vi.video_title,\n  vs.\"timestamp\",\n  vs.view_count\nFROM\n  youtube_stats.channel_info ci\nINNER JOIN\n  youtube_stats.video_info vi\nUSING\n  (channel_id)\nINNER JOIN\n  youtube_stats.video_stats vs\nUSING\n  (video_id)\nWHERE\n  ci.channel_name IN ($channel_info__channel_name) AND\n  $__timeFilter(vs.\"timestamp\")\n), cte_tag AS (\nSELECT\n  tag,\n  vi.video_id,\n  vi.video_title,\n  MAX(vi.view_count) AS view_count\nFROM\n  cte_video_list vi,\n  generate_series (\n    time_bucket(\n      '1 day', \n      (select timezone('Europe/Madrid', $__timeFrom()::timestamp with time zone))\n    ), time_bucket(\n      '1 day', \n      (select timezone('Europe/Madrid', $__timeTo()::timestamp with time zone))\n    ), '1 day'\n  ) tag\nWHERE\n  vi.timestamp >= tag AND\n  vi.timestamp <= tag + interval '1 day'\nGROUP BY\n  tag, vi.video_id, vi.video_title\n), cte_lag AS (\nSELECT\n  ct.tag,\n  ct.video_id,\n  ct.video_title,\n  ct.view_count,\n  LAG(ct.view_count, -1) OVER w AS last_view_count,\n  LAG(ct.tag, -1) OVER w AS last_tag\nFROM\n  cte_tag ct\nWINDOW w AS (PARTITION BY ct.video_id ORDER BY ct.tag DESC)\n), cte_daily_views AS (\nSELECT\n  cl.tag,\n  cl.video_id,\n  cl.video_title,\n  (cl.view_count - cl.last_view_count)/(cl.tag::DATE - cl.last_tag::DATE) AS daily_views\nFROM\n  cte_lag cl\nWHERE\n  cl.last_view_count IS NOT NULL\n), cte_limit AS (\nSELECT DISTINCT\n  video_id,\n  MAX(daily_views)\nFROM\n  cte_daily_views\nGROUP BY\n  video_id\nORDER BY\n  MAX(daily_views) DESC\nLIMIT\n  $limit\n)\nSELECT\n  video_title,\n  AVG(daily_views) AS \"Daily Views\",\n  tag AS time\nFROM\n  cte_daily_views\nWHERE\n  video_id IN (SELECT video_id FROM cte_limit)\nGROUP BY\n  video_title, tag\nORDER BY\n  time"
    }
   ]
  },
  {
   "title": "Last $limit Videos",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "WITH cte_video_list AS (\nSELECT DISTINCT\n  vi.video_id,\n  vi.video_title,\n  vi.video_creation_date\nFROM\n  youtube_stats.channel_info ci\nINNER JOIN\n  youtube_stats.video_info vi\nUSING\n  (channel_id)\nINNER JOIN\n  youtube_stats.video_stats vs\nUSING\n  (video_id)\nWHERE\n  ci.channel_name IN ($channel_info__channel_name) AND\n  $__timeFilter(vs.\"timestamp\")\nORDER BY\n  video_creation_date DESC\nLIMIT $limit\n), cte_tag AS (\nSELECT\n  vi.video_title,\n  MAX(vs.view_count) AS view_count,\n  tag\nFROM\n  cte_video_list vi\nINNER JOIN\n  youtube_stats.video_stats vs\nUSING\n  (video_id),\n  generate_series (\n    time_bucket(\n      '1 day', \n      (select timezone('Europe/Madrid', $__timeFrom()::timestamp with time zone))\n    ), time_bucket(\n      '1 day', \n      (select timezone('Europe/Madrid', $__timeTo()::timestamp with time zone))\n    ), '1 day'\n  ) tag\nWHERE\n  vs.timestamp >= tag AND\n  vs.timestamp <= tag + interval '1 day'\nGROUP BY\n  vi.video_title, tag\n)\nSELECT\n  video_title,\n  AVG(view_count) AS \"View Count\",\n  tag AS time\nFROM\n  cte_tag\nGROUP BY\n  video_title, tag\nORDER BY\n  time, MAX(view_count)"
    }
   ]
  }
 ]
}