{
 "title": "Youtube Channel Videos",
 "tags": [
  "youtube",
  "videos"
 ],
 "time": { "from": "now-14d/d", "to": "now/d" },
 "templating": {
  "list": [
   {
    "name": "channel_info__channel_name",
    "label": "Channel Name",
    "query": "WITH cte_channel_name AS (\nSELECT\n  channel_name\nFROM\n  youtube_stats.channel_info\nORDER BY\n  channel_name ASC\n)\nSELECT\n  channel_name\nFROM\n  cte_channel_name\nUNION ALL\nSELECT\n 'no data' AS channel_name\nFROM\n  (SELECT 1) a\nLEFT JOIN\n  cte_channel_name b ON FALSE\nWHERE\n  NOT EXISTS (SELECT 1 FROM cte_channel_name)"
   },
   {
    "name": "video_info__video_title",
    "label": "Video Title",
    "query": "WITH cte_video_title AS (\nSELECT\n  video_title\nFROM\n  youtube_stats.video_info\nWHERE\n  channel_id = ${channel_info__channel_id}\nORDER BY\n  video_title\n)\nSELECT\n  video_title\nFROM\n  cte_video_title\nUNION ALL\nSELECT\n 'no data' as video_title\nFROM\n  (SELECT 1) a\nLEFT JOIN\n  cte_video_title b ON FALSE\nWHERE\n  NOT EXISTS (SELECT 1 FROM cte_video_title)"
   },
   {
    "name": "channel_info__channel_id",
    "query": "WITH cte_channel_id AS (\nSELECT\n  channel_id\nFROM\n  youtube_stats.channel_info\nWHERE\n  channel_name = '${channel_info__channel_name}'\n)\nSELECT\n  channel_id\nFROM\n  cte_channel_id\nUNION ALL\nSELECT\n 0 AS channel_id\nFROM\n  (SELECT 1) a\nLEFT JOIN\n  cte_channel_id b ON FALSE\nWHERE\n  NOT EXISTS (SELECT 1 FROM cte_channel_id)"
   },
   {
    "name": "video_info__video_id",
    "query": "WITH cte_video_id AS (\nSELECT\n  video_id\nFROM\n  youtube_stats.video_info\nWHERE\n  video_title IN (${video_info__video_title})\n)\nSELECT\n  video_id\nFROM\n  cte_video_id\nUNION ALL\nSELECT\n 0 AS video_id\nFROM\n  (SELECT 1) a\nLEFT JOIN\n  cte_video_id b ON FALSE\nWHERE\n  NOT EXISTS (SELECT 1 FROM cte_video_id)"
   },
   {
    "name": "channel_info__channel_name_2",
    "label": "Channel Name 2",
    "query": "WITH cte_channel_name AS (\nSELECT\n  channel_name\nFROM\n  youtube_stats.channel_info\nWHERE\n  channel_name <> '${channel_info__channel_name}'\nORDER BY\n  channel_name ASC\n)\nSELECT\n  channel_name\nFROM\n  cte_channel_name\nUNION ALL\nSELECT\n 'no data' AS channel_name\nFROM\n  (SELECT 1) a\nLEFT JOIN\n  cte_channel_name b ON FALSE\nWHERE\n  NOT EXISTS (SELECT 1 FROM cte_channel_name)"
   },
   {
    "name": "channel_info__channel_id_2",
    "query": "WITH cte_channel_id AS (\nSELECT\n  channel_id\nFROM\n  youtube_stats.channel_info\nWHERE\n  channel_name = '${channel_info__channel_name_2}'\n)\nSELECT\n  channel_id\nFROM\n  cte_channel_id\nUNION ALL\nSELECT\n 0 AS channel_id\nFROM\n  (SELECT 1) a\nLEFT JOIN\n  cte_channel_id b ON FALSE\nWHERE\n  NOT EXISTS (SELECT 1 FROM cte_channel_id)"
   },
   {
    "name": "video_info__video_title_2",
    "label": "Video Title",
    "query": "WITH cte_video_title AS (\nSELECT\n  video_title\nFROM\n  youtube_stats.video_info\nWHERE\n  channel_id = ${channel_info__channel_id_2}\nORDER BY\n  video_title\n)\nSELECT\n  video_title\nFROM\n  cte_video_title\nUNION ALL\nSELECT\n 'no data' as video_title\nFROM\n  (SELECT 1) a\nLEFT JOIN\n  cte_video_title b ON FALSE\nWHERE\n  NOT EXISTS (SELECT 1 FROM cte_video_title)"
   },
   {
    "name": "video_info__video_id_2",
    "query": "WITH cte_video_id AS (\nSELECT\n  video_id\nFROM\n  youtube_stats.video_info\nWHERE\n  video_title IN (${video_info__video_title_2})\n)\nSELECT\n  video_id\nFROM\n  cte_video_id\nUNION ALL\nSELECT\n 0 AS video_id\nFROM\n  (SELECT 1) a\nLEFT JOIN\n  cte_video_id b ON FALSE\nWHERE\n  NOT EXISTS (SELECT 1 FROM cte_video_id)"
   }
  ]
 },
 "panels": [
  {
   "title": "Dynamic View Count",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "WITH cte_video_list AS (\nSELECT\n  vi.video_id,\n  vs.\"timestamp\"::DATE AS day,\n  MAX(vs.view_count) AS view_count\nFROM\n  youtube_stats.channel_info ci\nINNER JOIN\n  youtube_stats.video_info vi\nUSING\n  (channel_id)\nINNER JOIN\n  youtube_stats.video_stats vs\nUSING\n  (video_id)\nWHERE\n  ci.channel_name = '$channel_info__channel_name' AND\n  vi.video_id IN ($video_info__video_id) AND\n  $__timeFilter(vs.\"timestamp\")\nGROUP BY\n  vi.video_id,\n  day\n), cte_default AS (\nSELECT\n  *\nFROM\n  cte_video_list\nUNION ALL\n-- In case there is no data we indicate it in the chart\nSELECT DISTINCT\n  b.video_id,\n  gs.tag::DATE AS day,\n  0\nFROM\n  (SELECT generate_series (time_bucket('1 day', $__timeFrom()::timestamp with time zone), time_bucket('1 day', $__timeTo()::timestamp with time zone), '1 day') AS tag) gs,\n  cte_video_list b\nWHERE\n  gs.tag::DATE NOT IN (SELECT c.day FROM cte_video_list c WHERE b.video_id = c.video_id)\n), cte_partition AS (\nSELECT\n  video_id,\n  day,\n  view_count,\n  SUM(CASE WHEN view_count <> 0 THEN 1 ELSE 0 END) OVER (PARTITION BY video_id ORDER BY day) AS value_partition_asc,\n  SUM(CASE WHEN view_count <> 0 THEN 1 ELSE 0 END) OVER (PARTITION BY video_id ORDER BY day DESC) AS value_partition_desc\nFROM\n  cte_default\n), cte_prepare_interpolation AS (\nSELECT\n  video_id,\n  day,\n  view_count,\n  FIRST_VALUE(view_count) OVER (PARTITION BY video_id, value_partition_asc ORDER BY day) AS last_not_null_value,\n  FIRST_VALUE(day) OVER (PARTITION BY video_id, value_partition_asc ORDER BY day) AS last_not_null_date,\n  FIRST_VALUE(view_count) OVER (PARTITION BY video_id, value_partition_desc ORDER BY day DESC) AS first_next_not_null_value,\n  FIRST_VALUE(day) OVER (PARTITION BY video_id, value_partition_desc ORDER BY day DESC) AS first_next_not_null_date\nFROM\n  cte_partition\n), cte_interpolation AS (\nSELECT\n  vi.video_title,\n  TO_CHAR(cb.day, 'YYYY-MM-DD') AS day,\n  (CASE\n-- Linear interpolation\n    WHEN cb.first_next_not_null_value = 0 THEN cb.last_not_null_value\n    WHEN cb.last_not_null_value = 0 AND cb.day >= vi.video_creation_date::DATE\n      THEN cb.first_next_not_null_value/(cb.first_next_not_null_date - vi.video_creation_date::DATE) * (cb.day - vi.video_creation_date::DATE)\n    WHEN cb.last_not_null_value = 0 AND cb.day < vi.video_creation_date::DATE THEN 0\n    WHEN cb.view_count = 0 THEN cb.last_not_null_value + (cb.first_next_not_null_value - cb.last_not_null_value)/(cb.first_next_not_null_date - cb.last_not_null_date) * (cb.day - cb.last_not_null_date)\n    ELSE cb.view_count\n  END)::INTEGER AS view_count\nFROM\n  cte_prepare_interpolation cb\nINNER JOIN\n  youtube_stats.video_info vi \nON\n  cb.video_id = vi.video_id\n), cte_result AS (\nSELECT\n  video_title,\n  day,\n-- In case multiple videos have the same title or multiple values in a day\n  MAX(view_count) AS view_count\nFROM\n  cte_interpolation\nGROUP BY video_title, day\nORDER BY day ASC, view_count DESC\n)\nSELECT\n  video_title,\n  day,\n  view_count\nFROM\n  cte_result\nUNION ALL\nSELECT\n 'no_data' AS video_title,\n '2000-01-01' AS day,\n 0 AS view_count\nFROM\n  (SELECT 1) a\nLEFT JOIN\n  cte_result b ON FALSE\nWHERE\n  NOT EXISTS (SELECT 1 FROM cte_result)"
    }
   ]
  },
  {
   "title": "Dynamic View Count",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "WITH cte_video_list AS (\nSELECT\n  vi.video_id,\n  vs.\"timestamp\"::DATE AS day,\n  MAX(vs.view_count) AS view_count\nFROM\n  youtube_stats.channel_info ci\nINNER JOIN\n  youtube_stats.video_info vi\nUSING\n  (channel_id)\nINNER JOIN\n  youtube_stats.video_stats vs\nUSING\n  (video_id)\nWHERE\n  ci.channel_name = '$channel_info__channel_name_2' AND\n  vi.video_id IN ($video_info__video_id_2) AND\n  $__timeFilter(vs.\"timestamp\")\nGROUP BY\n  vi.video_id,\n  day\n), cte_default AS (\nSELECT\n  *\nFROM\n  cte_video_list\nUNION ALL\nSELECT DISTINCT\n  b.video_id,\n  gs.tag::DATE AS day,\n  0\nFROM\n  (SELECT generate_series (time_bucket('1 day', $__timeFrom()::timestamp with time zone), time_bucket('1 day', $__timeTo()::timestamp with time zone), '1 day') AS tag) gs,\n  cte_video_list b\nWHERE\n  gs.tag::DATE NOT IN (SELECT c.day FROM cte_video_list c WHERE b.video_id = c.video_id)\n), cte_partition AS (\nSELECT\n  video_id,\n  day,\n  view_count,\n  SUM(CASE WHEN view_count <> 0 THEN 1 ELSE 0 END) OVER (PARTITION BY video_id ORDER BY day) AS value_partition_asc,\n  SUM(CASE WHEN view_count <> 0 THEN 1 ELSE 0 END) OVER (PARTITION BY video_id ORDER BY day DESC) AS value_partition_desc\nFROM\n  cte_default\n), cte_prepare_interpolation AS (\nSELECT\n  video_id,\n  day,\n  view_count,\n  FIRST_VALUE(view_count) OVER (PARTITION BY video_id, value_partition_asc ORDER BY day) AS last_not_null_value,\n  FIRST_VALUE(day) OVER (PARTITION BY video_id, value_partition_asc ORDER BY day) AS last_not_null_date,\n  FIRST_VALUE(view_count) OVER (PARTITION BY video_id, value_partition_desc ORDER BY day DESC) AS first_next_not_null_value,\n  FIRST_VALUE(day) OVER (PARTITION BY video_id, value_partition_desc ORDER BY day DESC) AS first_next_not_null_date\nFROM\n  cte_partition\n), cte_interpolation AS (\nSELECT\n  vi.video_title,\n  TO_CHAR(cb.day, 'YYYY-MM-DD') AS day,\n  (CASE\n-- Linear interpolation\n    WHEN cb.first_next_not_null_value = 0 THEN cb.last_not_null_value\n    WHEN cb.last_not_null_value = 0 AND cb.day >= vi.video_creation_date::DATE\n      THEN cb.first_next_not_null_value/(cb.first_next_not_null_date - vi.video_creation_date::DATE) * (cb.day - vi.video_creation_date::DATE)\n    WHEN cb.last_not_null_value = 0 AND cb.day < vi.video_creation_date::DATE THEN 0\n    WHEN cb.view_count = 0 THEN cb.last_not_null_value + (cb.first_next_not_null_value - cb.last_not_null_value)/(cb.first_next_not_null_date - cb.last_not_null_date) * (cb.day - cb.last_not_null_date)\n    ELSE cb.view_count\n  END)::INTEGER AS view_count\nFROM\n  cte_prepare_interpolation cb\nINNER JOIN\n  youtube_stats.video_info vi \nON\n  cb.video_id = vi.video_id\n), cte_result AS (\nSELECT\n  video_title,\n  day,\n-- In case multiple videos have the same title or multiple values in a day\n  MAX(view_count) AS view_count\nFROM\n  cte_interpolation\nGROUP BY video_title, day\nORDER BY day ASC, view_count DESC\n)\nSELECT\n  video_title,\n  day,\n  view_count\nFROM\n  cte_result\nUNION ALL\nSELECT\n 'no_data' AS video_title,\n '2000-01-01' AS day,\n 0 AS view_count\nFROM\n  (SELECT 1) a\nLEFT JOIN\n  cte_result b ON FALSE\nWHERE\n  NOT EXISTS (SELECT 1 FROM cte_result)"
    }
   ]
  },
  {
   "title": "Daily View Count",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "WITH cte_video_list AS (\nSELECT\n  vi.video_title,\n  vs.\"timestamp\"::DATE AS day,\n  MAX(vs.view_count) AS view_count\nFROM\n  youtube_stats.channel_info ci\nINNER JOIN\n  youtube_stats.video_info vi\nUSING\n  (channel_id)\nINNER JOIN\n  youtube_stats.video_stats vs\nUSING\n  (video_id)\nWHERE\n  ci.channel_name = '$channel_info__channel_name' AND\n  vi.video_id IN ($video_info__video_id) AND\n  vs.\"timestamp\" >= ($__timeFrom()::timestamp with time zone - INTERVAL '7 days') AND\n  vs.\"timestamp\" <= $__timeTo()::timestamp with time zone\nGROUP BY\n  vi.video_title,\n  day\n), cte_lag AS (\nSELECT\n  ct.day,\n  ct.video_title,\n  ct.view_count,\n  LAG(ct.view_count, -1) OVER w AS last_view_count,\n  LAG(ct.day, -1) OVER w AS last_day\nFROM\n  cte_video_list ct\nWINDOW w AS (PARTITION BY ct.video_title ORDER BY ct.day DESC)\n), cte_daily_views AS (\nSELECT\n  cl.video_title,\n  (cl.view_count - cl.last_view_count)/(cl.day - cl.last_day) AS daily_views,\n  generate_series(\n-- First day is not taken into account as it is part of the previous window.\n\t  cl.last_day + INTERVAL '1 day',\n    cl.day, INTERVAL '1 day'\n  ) AS day\nFROM\n  cte_lag cl\nWHERE\n  cl.last_view_count IS NOT NULL\n), cte_result AS (\nSELECT\n  video_title,\n  AVG(daily_views) AS daily_views,\n  TO_CHAR(day,'YYYY-MM-DD') AS day\nFROM\n  cte_daily_views\nGROUP BY\n  video_title, day\nORDER BY\n  day, daily_views DESC\n)\nSELECT\n  video_title,\n  daily_views,\n  day\nFROM\n  cte_result\nUNION ALL\n-- In case there is no data we indicate it in the chart\nSELECT\n 'no_data' AS video_title,\n 0 AS daily_views,\n '2000-01-01' AS day\nFROM\n  (SELECT 1) a\nLEFT JOIN\n  cte_result b ON FALSE\nWHERE\n  NOT EXISTS (SELECT 1 FROM cte_result)"
    }
   ]
  },
  {
   "title": "Daily View Count",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "rawSql": "WITH cte_video_list AS (\nSELECT\n  vi.video_title,\n  vs.\"timestamp\"::DATE AS day,\n  MAX(vs.view_count) AS view_count\nFROM\n  youtube_stats.channel_info ci\nINNER JOIN\n  youtube_stats.video_info vi\nUSING\n  (channel_id)\nINNER JOIN\n  youtube_stats.video_stats vs\nUSING\n  (video_id)\nWHERE\n  ci.channel_name = '$channel_info__channel_name_2' AND\n  vi.video_id IN ($video_info__video_id_2) AND\n  $__timeFilter(vs.\"timestamp\")\nGROUP BY\n  vi.video_title,\n  day\n), cte_lag AS (\nSELECT\n  ct.day,\n  ct.video_title,\n  ct.view_count,\n  LAG(ct.view_count, -1) OVER w AS last_view_count,\n  LAG(ct.day, -1) OVER w AS last_day\nFROM\n  cte_video_list ct\nWINDOW w AS (PARTITION BY ct.video_title ORDER BY ct.day DESC)\n), cte_daily_views AS (\nSELECT\n  cl.video_title,\n  (cl.view_count - cl.last_view_count)/(cl.day - cl.last_day) AS daily_views,\n  generate_series(\n-- First day is not taken into account as it is part of the previous window.\n\t  cl.last_day + INTERVAL '1 day',\n    cl.day, INTERVAL '1 day'\n  ) AS day\nFROM\n  cte_lag cl\nWHERE\n  cl.last_view_count IS NOT NULL\n), cte_result AS (\nSELECT\n  video_title,\n  AVG(daily_views) AS daily_views,\n  TO_CHAR(day,'YYYY-MM-DD') AS day\nFROM\n  cte_daily_views\nGROUP BY\n  video_title, day\nORDER BY\n  day, daily_views DESC\n)\nSELECT\n  video_title,\n  daily_views,\n  day\nFROM\n  cte_result\nUNION ALL\n-- In case there is no data we indicate it in the chart\nSELECT\n 'no_data' AS video_title,\n 0 AS daily_views,\n '2000-01-01' AS day\nFROM\n  (SELECT 1) a\nLEFT JOIN\n  cte_result b ON FALSE\nWHERE\n  NOT EXISTS (SELECT 1 FROM cte_result)"
    }
   ]
  },
  {
   "title": "Dynamic View Count",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 19, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "rawSql": "WITH cte_video_list AS (\nSELECT\n  vi.video_id,\n  vs.\"timestamp\"::DATE AS day,\n  MAX(vs.view_count) AS view_count\nFROM\n  youtube_stats.channel_info ci\nINNER JOIN\n  youtube_stats.video_info vi\nUSING\n  (channel_id)\nINNER JOIN\n  youtube_stats.video_stats vs\nUSING\n  (video_id)\nWHERE\n  ci.channel_name = '$channel_info__channel_name' AND\n  vi.video_id IN ($video_info__video_id) AND\n  $__timeFilter(vs.\"timestamp\")\nGROUP BY\n  vi.video_id,\n  day\n), cte_default AS (\nSELECT\n  *\nFROM\n  cte_video_list\nUNION ALL\nSELECT DISTINCT\n  b.video_id,\n  gs.tag::DATE AS day,\n  0\nFROM\n  (SELECT generate_series (time_bucket('1 day', $__timeFrom()::timestamp with time zone), time_bucket('1 day', $__timeTo()::timestamp with time zone), '1 day') AS tag) gs,\n  cte_video_list b\nWHERE\n  gs.tag::DATE NOT IN (SELECT c.day FROM cte_video_list c WHERE b.video_id = c.video_id)\n), cte_partition AS (\nSELECT\n  video_id,\n  day,\n  view_count,\n  SUM(CASE WHEN view_count <> 0 THEN 1 ELSE 0 END) OVER (PARTITION BY video_id ORDER BY day) AS value_partition_asc,\n  SUM(CASE WHEN view_count <> 0 THEN 1 ELSE 0 END) OVER (PARTITION BY video_id ORDER BY day DESC) AS value_partition_desc\nFROM\n  cte_default\n), cte_prepare_interpolation AS (\nSELECT\n  video_id,\n  day,\n  view_count,\n  FIRST_VALUE(view_count) OVER (PARTITION BY video_id, value_partition_asc ORDER BY day) AS last_not_null_value,\n  FIRST_VALUE(day) OVER (PARTITION BY video_id, value_partition_asc ORDER BY day) AS last_not_null_date,\n  FIRST_VALUE(view_count) OVER (PARTITION BY video_id, value_partition_desc ORDER BY day DESC) AS first_next_not_null_value,\n  FIRST_VALUE(day) OVER (PARTITION BY video_id, value_partition_desc ORDER BY day DESC) AS first_next_not_null_date\nFROM\n  cte_partition\n), cte_interpolation AS (\nSELECT\n  vi.video_title,\n  TO_CHAR(cb.day, 'YYYY-MM-DD') AS day,\n-- Linear interpolation\n  (CASE\n    WHEN cb.first_next_not_null_value = 0 THEN cb.last_not_null_value\n    WHEN cb.last_not_null_value = 0 AND cb.day >= vi.video_creation_date::DATE\n      THEN cb.first_next_not_null_value/(cb.first_next_not_null_date - vi.video_creation_date::DATE) * (cb.day - vi.video_creation_date::DATE)\n    WHEN cb.last_not_null_value = 0 AND cb.day < vi.video_creation_date::DATE THEN 0\n    WHEN cb.view_count = 0 THEN cb.last_not_null_value + (cb.first_next_not_null_value - cb.last_not_null_value)/(cb.first_next_not_null_date - cb.last_not_null_date) * (cb.day - cb.last_not_null_date)\n    ELSE cb.view_count\n  END)::INTEGER AS view_count\nFROM\n  cte_prepare_interpolation cb\nINNER JOIN\n  youtube_stats.video_info vi \nON\n  cb.video_id = vi.video_id\n), cte_result AS (\nSELECT\n  video_title,\n  day,\n-- In case multiple videos have the same title or multiple values in a day\n  MAX(view_count) AS view_count\nFROM\n  cte_interpolation\nGROUP BY video_title, day\nORDER BY day ASC, view_count DESC\n)\nSELECT\n  video_title,\n  day,\n  view_count\nFROM\n  cte_result\nUNION ALL\n-- In case there is no data we indicate it in the chart\nSELECT\n 'no_data' AS video_title,\n '2000-01-01' AS day,\n 0 AS view_count\nFROM\n  (SELECT 1) a\nLEFT JOIN\n  cte_result b ON FALSE\nWHERE\n  NOT EXISTS (SELECT 1 FROM cte_result)"
    }
   ]
  },
  {
   "title": "Dynamic Daily Views",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 19, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "rawSql": "WITH cte_video_list AS (\nSELECT\n  vi.video_id,\n  vs.\"timestamp\"::DATE AS day,\n  MAX(vs.view_count) AS view_count\nFROM\n  youtube_stats.channel_info ci\nINNER JOIN\n  youtube_stats.video_info vi\nUSING\n  (channel_id)\nINNER JOIN\n  youtube_stats.video_stats vs\nUSING\n  (video_id)\nWHERE\n  ci.channel_name = '$channel_info__channel_name_2' AND\n  vi.video_id IN ($video_info__video_id_2) AND\n  $__timeFilter(vs.\"timestamp\")\nGROUP BY\n  vi.video_id,\n  day\n), cte_default AS (\nSELECT\n  *\nFROM\n  cte_video_list\nUNION ALL\nSELECT DISTINCT\n  b.video_id,\n  gs.tag::DATE AS day,\n  0\nFROM\n  (SELECT generate_series (time_bucket('1 day', $__timeFrom()::timestamp with time zone), time_bucket('1 day', $__timeTo()::timestamp with time zone), '1 day') AS tag) gs,\n  cte_video_list b\nWHERE\n  gs.tag::DATE NOT IN (SELECT c.day FROM cte_video_list c WHERE b.video_id = c.video_id)\n), cte_partition AS (\nSELECT\n  video_id,\n  day,\n  view_count,\n  SUM(CASE WHEN view_count <> 0 THEN 1 ELSE 0 END) OVER (PARTITION BY video_id ORDER BY day) AS value_partition_asc,\n  SUM(CASE WHEN view_count <> 0 THEN 1 ELSE 0 END) OVER (PARTITION BY video_id ORDER BY day DESC) AS value_partition_desc\nFROM\n  cte_default\n), cte_prepare_interpolation AS (\nSELECT\n  video_id,\n  day,\n  view_count,\n  FIRST_VALUE(view_count) OVER (PARTITION BY video_id, value_partition_asc ORDER BY day) AS last_not_null_value,\n  FIRST_VALUE(day) OVER (PARTITION BY video_id, value_partition_asc ORDER BY day) AS last_not_null_date,\n  FIRST_VALUE(view_count) OVER (PARTITION BY video_id, value_partition_desc ORDER BY day DESC) AS first_next_not_null_value,\n  FIRST_VALUE(day) OVER (PARTITION BY video_id, value_partition_desc ORDER BY day DESC) AS first_next_not_null_date\nFROM\n  cte_partition\n), cte_interpolation AS (\nSELECT\n  vi.video_title,\n  TO_CHAR(cb.day, 'YYYY-MM-DD') AS day,\n-- Linear interpolation\n  (CASE\n    WHEN cb.first_next_not_null_value = 0 THEN cb.last_not_null_value\n    WHEN cb.last_not_null_value = 0 AND cb.day >= vi.video_creation_date::DATE\n      THEN cb.first_next_not_null_value/(cb.first_next_not_null_date - vi.video_creation_date::DATE) * (cb.day - vi.video_creation_date::DATE)\n    WHEN cb.last_not_null_value = 0 AND cb.day < vi.video_creation_date::DATE THEN 0\n    WHEN cb.view_count = 0 THEN cb.last_not_null_value + (cb.first_next_not_null_value - cb.last_not_null_value)/(cb.first_next_not_null_date - cb.last_not_null_date) * (cb.day - cb.last_not_null_date)\n    ELSE cb.view_count\n  END)::INTEGER AS view_count\nFROM\n  cte_prepare_interpolation cb\nINNER JOIN\n  youtube_stats.video_info vi \nON\n  cb.video_id = vi.video_id\n), cte_result AS (\nSELECT\n  video_title,\n  day,\n-- In case multiple videos have the same title or multiple values in a day\n  MAX(view_count) AS view_count\nFROM\n  cte_interpolation\nGROUP BY video_title, day\nORDER BY day ASC, view_count DESC\n)\nSELECT\n  video_title,\n  day,\n  view_count\nFROM\n  cte_result\nUNION ALL\n-- In case there is no data we indicate it in the chart\nSELECT\n 'no_data' AS video_title,\n '2000-01-01' AS day,\n 0 AS view_count\nFROM\n  (SELECT 1) a\nLEFT JOIN\n  cte_result b ON FALSE\nWHERE\n  NOT EXISTS (SELECT 1 FROM cte_result)"
    }
   ]
  }
 ]
}