{
 "title": "Youtube Channel Analysis Advanced",
 "tags": [
  "youtube",
  "channel"
 ],
 "time": { "from": "now-1y/d", "to": "now/d" },
 "templating": {
  "list": [
   {
    "name": "channel_info__channel_name",
    "label": "Channel Name",
    "query": "WITH cte_channel_name AS (\nSELECT\n  channel_name\nFROM\n  youtube_stats.channel_info\nORDER BY\n  channel_name ASC\n)\nSELECT\n  channel_name\nFROM\n  cte_channel_name\nUNION ALL\nSELECT\n 'no data' AS channel_name\nFROM\n  (SELECT 1) a\nLEFT JOIN\n  cte_channel_name b ON FALSE\nWHERE\n  NOT EXISTS (SELECT 1 FROM cte_channel_name)"
   }
  ]
 },
 "panels": [
  { "title": "${channel_info__channel_name}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "channel_info__channel_name" },
  {
   "title": "Video List ordered by View Count",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "WITH cte_top AS (\nSELECT\n  vi.video_title,\n  vs.view_count,\n  RANK() OVER w,\n  SUM(vs.view_count) OVER w,\n  RANK() OVER (PARTITION BY vi.video_title ORDER BY vs.view_count DESC) AS same_title\nFROM\n  youtube_stats.channel_info ci\nINNER JOIN\n  youtube_stats.video_info vi\nON\n  (vi.channel_id = ci.channel_id)\nINNER JOIN\n  youtube_stats.video_stats vs\nON\n  (vi.video_id = vs.video_id)\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  ci.channel_name IN ($channel_info__channel_name) AND\n  vs.\"timestamp\" = (SELECT MAX(\"timestamp\") FROM youtube_stats.video_stats WHERE video_id = vi.video_id)\nWINDOW w AS (ORDER BY vs.view_count DESC)\nORDER BY\n  vs.view_count DESC\n), cte_result AS (\nSELECT\n  ct.video_title || (CASE WHEN ct.same_title != 1 THEN ('_' || ct.same_title) ELSE '' END) AS video_title,\n  ct.view_count,\n-- Page-by-page separation using an ad-hoc filter that prevents the list of videos for each page from becoming so large that it exceeds the size of the tooltip.\n  CASE\n    WHEN ct.rank <= 4 THEN 'Page 1'\n    WHEN (ct.sum <= (t.sum * 2)) AND (ct.rank < 20) THEN 'Page 2'\n    WHEN (ct.sum <= (t.sum * 3)) AND (ct.rank < (20 * 1 + 10)) THEN 'Page 3'\n    WHEN (ct.sum <= (t.sum * 4)) AND (ct.rank < (20 * 2 + 10)) THEN 'Page 4'\n    WHEN (ct.sum <= (t.sum * 5)) AND (ct.rank < (20 * 3 + 10)) THEN 'Page 5'\n    WHEN (ct.sum <= (t.sum * 6)) AND (ct.rank < (20 * 4 + 10)) THEN 'Page 6'\n    WHEN (ct.sum <= (t.sum * 7)) AND (ct.rank < (20 * 5 + 10)) THEN 'Page 7'\n    WHEN (ct.sum <= (t.sum * 8)) AND (ct.rank < (20 * 6 + 10)) THEN 'Page 8'\n    WHEN (ct.sum <= (t.sum * 9)) AND (ct.rank < (20 * 7 + 10)) THEN 'Page 9'\n    WHEN (ct.sum <= (t.sum * 10)) AND (ct.rank < (20 * 8 + 10)) THEN 'Page 10'\n    WHEN (ct.sum <= (t.sum * 11)) AND (ct.rank < (20 * 9 + 10)) THEN 'Page 11'\n    WHEN (ct.sum <= (t.sum * 12)) AND (ct.rank < (20 * 10 + 10)) THEN 'Page 12'\n    WHEN (ct.sum <= (t.sum * 13)) AND (ct.rank < (20 * 11 + 10)) THEN 'Page 13'\n    WHEN (ct.sum <= (t.sum * 14)) AND (ct.rank < (20 * 12 + 10)) THEN 'Page 14'\n    WHEN (ct.sum <= (t.sum * 14)) AND (ct.rank < (20 * 13 + 10)) THEN 'Page 15'\n    WHEN (ct.sum <= (t.sum * 14)) AND (ct.rank < (20 * 14 + 10)) THEN 'Page 16'\n    WHEN (ct.sum <= (t.sum * 14)) AND (ct.rank < (20 * 15 + 10)) THEN 'Page 17'\n    WHEN (ct.sum <= (t.sum * 14)) AND (ct.rank < (20 * 16 + 10)) THEN 'Page 18'\n    WHEN (ct.sum <= (t.sum * 14)) AND (ct.rank < (20 * 17 + 10)) THEN 'Page 19'\n    WHEN (ct.sum <= (t.sum * 14)) AND (ct.rank < (20 * 18 + 10)) THEN 'Page 20'\n    WHEN (ct.sum <= (t.sum * 14)) AND (ct.rank < (20 * 19 + 10)) THEN 'Page 21'\n    WHEN (ct.sum <= (t.sum * 14)) AND (ct.rank < (20 * 20 + 10)) THEN 'Page 22'\n    WHEN (ct.sum <= (t.sum * 14)) AND (ct.rank < (20 * 21 + 10)) THEN 'Page 23'\n    WHEN (ct.sum <= (t.sum * 14)) AND (ct.rank < (20 * 22 + 10)) THEN 'Page 24'\n    WHEN (ct.sum <= (t.sum * 14)) AND (ct.rank < (20 * 23 + 10)) THEN 'Page 25'\n    WHEN (ct.sum <= (t.sum * 14)) AND (ct.rank < (20 * 24 + 10)) THEN 'Page 26'\n    WHEN (ct.sum <= (t.sum * 14)) AND (ct.rank < (20 * 25 + 10)) THEN 'Page 27'\n    WHEN (ct.sum <= (t.sum * 14)) AND (ct.rank < (20 * 26 + 10)) THEN 'Page 28'\n    WHEN (ct.sum <= (t.sum * 14)) AND (ct.rank < (20 * 27 + 10)) THEN 'Page 29'\n    WHEN (ct.sum <= (t.sum * 14)) AND (ct.rank < (20 * 28 + 10)) THEN 'Page 30'\n    ELSE 'rest'\n  END AS top\nFROM\n  cte_top ct,\n  (SELECT sum FROM cte_top WHERE rank = 4) t\nWHERE\n  ct.view_count <> 0\nORDER BY\n  ct.rank\n)\nSELECT\n  video_title,\n  view_count,\n  top\nFROM\n  cte_result\nUNION ALL\n-- In case there is no data we indicate it in the chart\nSELECT\n 'no data' AS video_title,\n 0 AS view_count,\n 'Page 0' AS top\nFROM\n  (SELECT 1) a\nLEFT JOIN\n  cte_result b ON FALSE\nWHERE\n  NOT EXISTS (SELECT 1 FROM cte_result)"
    }
   ]
  },
  {
   "title": "Daily Views",
   "type": "barchart",
   "gridPos": { "h": 15, "w": 23, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "WITH cte_video_list AS (\nSELECT\n  vi.video_id,\n  vs.\"timestamp\"::DATE AS day,\n  MAX(vs.view_count) AS view_count\nFROM\n  youtube_stats.channel_info ci\nINNER JOIN\n  youtube_stats.video_info vi\nUSING\n  (channel_id)\nINNER JOIN\n  youtube_stats.video_stats vs\nUSING\n  (video_id)\nWHERE\n  ci.channel_name IN ($channel_info__channel_name) AND\n  $__timeFilter(vs.\"timestamp\")\nGROUP BY\n  video_id, day\n), cte_lag AS (\nSELECT\n  ct.day,\n  ct.video_id,\n  ct.view_count,\n  LAG(ct.view_count, -1) OVER w AS last_view_count,\n  LAG(ct.day, -1) OVER w AS last_day\nFROM\n  cte_video_list ct\nWINDOW w AS (PARTITION BY ct.video_id ORDER BY ct.day DESC)\n), cte_daily_views AS (\nSELECT\n  cl.video_id,\n  (cl.view_count - cl.last_view_count)/(cl.day - cl.last_day) AS daily_views,\n  TO_CHAR(generate_series(\n-- First day is not taken into account as it is part of the previous window.\n\t  cl.last_day + INTERVAL '1 day',\n    cl.day, INTERVAL '1 day'\n  ),'YYYY-MM-DD') AS day\nFROM\n  cte_lag cl\nWHERE\n  cl.last_view_count IS NOT NULL\n)\nSELECT\n  SUM(daily_views) AS \"Daily Views\",\n  day\nFROM\n  cte_daily_views\nGROUP BY\n  day\nORDER BY\n  day"
    }
   ]
  },
  {
   "title": "Average Daily Views by Week",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "rawSql": "WITH cte_video_list AS (\nSELECT DISTINCT\n  vi.video_id,\n  vs.\"timestamp\",\n  vs.view_count\nFROM\n  youtube_stats.channel_info ci\nINNER JOIN\n  youtube_stats.video_info vi\nUSING\n  (channel_id)\nINNER JOIN\n  youtube_stats.video_stats vs\nUSING\n  (video_id)\nWHERE\n  ci.channel_name IN ($channel_info__channel_name) AND\n  $__timeFilter(vs.\"timestamp\")\n), cte_tag AS (\nSELECT\n  tag,\n  vi.video_id,\n  MAX(vi.view_count) AS view_count\nFROM\n  cte_video_list vi,\n  generate_series (\n    time_bucket(\n      '1 day', \n      (select timezone('Europe/Madrid', $__timeFrom()::timestamp with time zone))\n    ), time_bucket(\n      '1 day', \n      (select timezone('Europe/Madrid', $__timeTo()::timestamp with time zone))\n    ), '1 day'\n  ) tag\nWHERE\n  vi.timestamp >= tag AND\n  vi.timestamp <= tag + interval '1 day'\nGROUP BY\n  tag, vi.video_id\n), cte_lag AS (\nSELECT\n  ct.tag,\n  ct.video_id,\n  ct.view_count,\n  LAG(ct.view_count, -1) OVER w AS last_view_count,\n  LAG(ct.tag, -1) OVER w AS last_tag\nFROM\n  cte_tag ct\nWINDOW w AS (PARTITION BY ct.video_id ORDER BY ct.tag DESC)\n), cte_daily_views AS (\nSELECT\n  cl.tag, \n  cl.video_id,\n  (cl.view_count - cl.last_view_count)/(cl.tag::DATE - cl.last_tag::DATE) AS daily_views\nFROM\n  cte_lag cl\nWHERE\n  cl.last_view_count IS NOT NULL\n), cte_result AS (\nSELECT\n  TO_CHAR(tag, 'YYYY') AS year,\n  AVG(daily_views) AS daily_views,\n-- Add understandability to the data by putting in the month in which the Monday of that week is located\n-- (DATE - DOW) -> Return latest Sunday, but we want to get latest Monday since Week Number (IW) understand the start of the week on Monday\n  TO_CHAR(tag, 'IW') || ' (' || TO_CHAR(tag - INTERVAL '1 day' * MOD((EXTRACT(DOW FROM tag)+6),7), 'FMMonth') || ')' AS week\nFROM\n  cte_daily_views\nGROUP BY \n  TO_CHAR(tag, 'YYYY'),\n  TO_CHAR(tag, 'IW'),\n  TO_CHAR(tag - INTERVAL '1 day' * MOD((EXTRACT(DOW FROM tag)+6),7), 'FMMonth')\nORDER BY\n  TO_CHAR(tag, 'YYYY'),\n  TO_CHAR(tag, 'IW') ASC\n)\nSELECT\n  year,\n  daily_views,\n  week\nFROM\n  cte_result\nUNION ALL\n-- In case there is no data we indicate it in the chart\nSELECT\n '2000' AS video_title,\n 0 AS daily_views,\n '0' AS week\nFROM\n  (SELECT 1) a\nLEFT JOIN\n  cte_result b ON FALSE\nWHERE\n  NOT EXISTS (SELECT 1 FROM cte_result)"
    }
   ]
  },
  {
   "title": "Average Daily Views by Day of Week",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "rawSql": "WITH cte_video_list AS (\nSELECT DISTINCT\n  vi.video_id,\n  vs.\"timestamp\",\n  vs.view_count\nFROM\n  youtube_stats.channel_info ci\nINNER JOIN\n  youtube_stats.video_info vi\nUSING\n  (channel_id)\nINNER JOIN\n  youtube_stats.video_stats vs\nUSING\n  (video_id)\nWHERE\n  ci.channel_name IN ($channel_info__channel_name) AND\n  $__timeFilter(vs.\"timestamp\")\n), cte_tag AS (\nSELECT\n  tag,\n  vi.video_id,\n  MAX(vi.view_count) AS view_count\nFROM\n  cte_video_list vi,\n  generate_series (\n    time_bucket(\n      '1 day', \n      (select timezone('Europe/Madrid', $__timeFrom()::timestamp with time zone))\n    ), time_bucket(\n      '1 day', \n      (select timezone('Europe/Madrid', $__timeTo()::timestamp with time zone))\n    ), '1 day'\n  ) tag\nWHERE\n  vi.timestamp >= tag AND\n  vi.timestamp <= tag + interval '1 day'\nGROUP BY\n  tag, vi.video_id\n), cte_lag AS (\nSELECT\n  ct.tag,\n  ct.video_id,\n  ct.view_count,\n  LAG(ct.view_count, -1) OVER w AS last_view_count,\n  LAG(ct.tag, -1) OVER w AS last_tag\nFROM\n  cte_tag ct\nWINDOW w AS (PARTITION BY ct.video_id ORDER BY ct.tag DESC)\n), cte_daily_views AS (\nSELECT\n  cl.tag,\n  cl.video_id,\n  (cl.view_count - cl.last_view_count)/(cl.tag::DATE - cl.last_tag::DATE) AS daily_views\nFROM\n  cte_lag cl\nWHERE\n  cl.last_view_count IS NOT NULL\n), cte_result AS (\nSELECT\n  TO_CHAR(tag, 'YYYY') AS year,\n  AVG(daily_views) AS daily_views,\n  TO_CHAR(tag, 'Day') AS day,\n  EXTRACT(DOW FROM tag) AS dow\nFROM\n  cte_daily_views\nGROUP BY \n  TO_CHAR(tag, 'YYYY'),\n  TO_CHAR(tag, 'Day'),\n  EXTRACT(DOW FROM tag)\nORDER BY\n  EXTRACT(DOW FROM tag)\n)\nSELECT\n  year,\n  daily_views,\n  day,\n  dow\nFROM\n  cte_result\nUNION ALL\n-- In case there is no data we indicate it in the chart\nSELECT\n '2000' AS video_title,\n 0 AS daily_views,\n 'Sunday' AS week,\n 0 AS dow\nFROM\n  (SELECT 1) a\nLEFT JOIN\n  cte_result b ON FALSE\nWHERE\n  NOT EXISTS (SELECT 1 FROM cte_result)"
    }
   ]
  }
 ]
}